import Link from 'next/link'
import { code } from '@/components/features/demo/three-examples/shared'

/** Brooklyn Dead: the neighbouring 3D work, and where it meets this one. */
export function BrooklynDeadSection() {
  return (
    <section className="space-y-4">
      <h2 className="aka-lead">
        Brooklyn Dead: the same geometry, a different runtime
      </h2>
      <p>
        The other 3D work on this site is{' '}
        <Link href="/demo/blenderpipeline" className="aka-quiet-link">
          Brooklyn Dead
        </Link>
        , and it earns a section here for the contrast rather than the overlap. Nothing in that
        project runs Three.js: geometry is generated by Blender&apos;s Python API, exported as{' '}
        <code className={code}>glTF 2.0</code>, and rendered by Godot 4.
      </p>
      <p>
        What connects them is that export format. glTF is the interchange format Three.js loads
        natively through <code className={code}>GLTFLoader</code>, so an asset that satisfies that
        pipeline&apos;s validators is already a web asset: the same file the game opens would drop
        into the scene on this page. That is why Three.js sits in that project&apos;s skill list
        next to Godot. The pipeline targets a format, not an engine.
      </p>
      <p>
        The difference is worth stating plainly, because it is where the two halves of 3D work
        actually diverge. Everything on this page computes its geometry live, on the GPU, from a
        handful of uniforms, and nothing survives the frame it was drawn in. That pipeline does the
        opposite: geometry is written ahead of time by a Python file, gated by validators that
        refuse a bad rebuild, and handed to an engine as an asset on disk. One is a surface you are
        drawing right now; the other is a thing you made that has to still be correct tomorrow.
      </p>
    </section>
  )
}
