/**
 * Build-time blur placeholders for images referenced by path.
 *
 * next/image generates a blurDataURL automatically for a *static import*,
 * because the file is in the module graph and can be inspected. Every image on
 * a write-up is referenced as a string path instead, so it gets no placeholder
 * at all: the frame is empty until the lazy image decodes, then snaps in.
 *
 * This precomputes the same thing for path-referenced images — a 16px WebP,
 * base64'd — into a module DemoImage reads. The map is only ever evaluated on
 * the server, so a page's HTML carries the one string it needs and the client
 * never receives the map.
 */
import { execSync } from 'node:child_process'
import { readdirSync, statSync, writeFileSync, readFileSync, mkdtempSync } from 'node:fs'
import { join, extname } from 'node:path'
import { tmpdir } from 'node:os'

const ROOT = 'public'
const OK = new Set(['.webp', '.png', '.jpg', '.jpeg'])
const tmp = mkdtempSync(join(tmpdir(), 'blur-'))

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e)
    if (statSync(p).isDirectory()) walk(p, out)
    else if (OK.has(extname(p).toLowerCase())) out.push(p)
  }
  return out
}

const map = {}
let skipped = 0
for (const file of walk(ROOT)) {
  const url = '/' + file.slice(ROOT.length + 1)
  const out = join(tmp, 'b.webp')
  try {
    // 16px wide keeps the payload around 200 bytes; any larger and the
    // placeholder starts costing more than the flash it prevents.
    execSync(`cwebp -quiet -resize 16 0 -q 40 "${file}" -o "${out}"`, { stdio: 'ignore' })
    map[url] = `data:image/webp;base64,${readFileSync(out).toString('base64')}`
  } catch {
    skipped++
  }
}

const body = `/* Generated by tools/gen-blur.mjs. Do not edit by hand. */
export const BLUR: Record<string, string> = ${JSON.stringify(map, null, 2)}
`
writeFileSync('lib/blur-map.generated.ts', body)
const bytes = Buffer.byteLength(body)
console.log(`${Object.keys(map).length} placeholders, ${skipped} skipped, ${(bytes / 1024).toFixed(1)} kB module`)
